# Generated by Django 5.0.4 on 2024-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("text", models.TextField(max_length=2000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updates", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
