# Generated by Django 5.0.4 on 2024-04-27 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="updates",
            new_name="updated",
        ),
    ]
