# Generated by Django 5.0.4 on 2024-04-27 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_rename_updates_note_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="text",
            new_name="content",
        ),
    ]
